language: php
php:
  - 5.6
  - 5.5
  - 5.4
  - 5.3
  
# install vanilla CI 2.2 before anything
before_install:
  - wget https://github.com/EllisLab/CodeIgniter/archive/2.2.0.zip -O /tmp/codeigniter-2.2.0.zip
  - unzip /tmp/codeigniter-2.2.0.zip
  - mv CodeIgniter-2.2.0/application ./application
  - mv CodeIgniter-2.2.0/system ./system
  - mv CodeIgniter-2.2.0/index.php index.php
  
# install this project on top of it
install:
  - wget https://github.com/fmalk/codeigniter-phpunit/archive/master.zip -O /tmp/codeigniter-phpunit.zip
  - unzip /tmp/codeigniter-phpunit.zip
  - mv codeigniter-phpunit-master/application/tests ./application/tests
  - mv codeigniter-phpunit-master/system/core/CodeIgniter.php ./system/core/CodeIgniter.php
  - mv codeigniter-phpunit-master/system/core/Utf8.php ./system/core/Utf8.php
  - mv codeigniter-phpunit-master/phpunit.xml phpunit.xml