language: php
php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm

# install vanilla CI 2.2-stable before anything
before_install:
  - wget https://github.com/bcit-ci/CodeIgniter/archive/2.2-stable.tar.gz -O - | tar xz
  - cp -r application/* CodeIgniter-2.2-stable/application/
  - cp -r system/* CodeIgniter-2.2-stable/system/

# install this project on top of it
install:
  - cp -r CodeIgniter-2.2-stable/system/* system/
  - cp -r CodeIgniter-2.2-stable/application/* application/
  - mv CodeIgniter-2.2-stable/index.php index.php
  - rm -rf CodeIgniter-2.2-stable

# run multiple test commands
script:
  - phpunit                  #default test command
  - phpunit -c phpunit.xml   #custom test command to make sure CLI args don't break the test
